// The End-of-Sprint Test on the server: window settings, attempts, autosave, grading, leaderboard.
// Questions (with answers) live only on the server, in data/sprint-test.json (generated by `npm run build:portal`).
import fs from 'node:fs';
import { config } from './config.js';
import { one, all, run, getSetting, parseJSON } from './db.js';
import * as kv from './kv.js';
import { runTests } from './grader.js';
import { maskRoll } from './security.js';

// Marks per question type. MCQ: 1 each. Coding: partial credit by hidden tests passed.
// Written problems ("reviewed by panel"): awarded by an admin, 0..MARKS.text each.
export const MARKS = { mcq: 1, code: 1, text: 1 };

// The built-in set from the portal HTML (npm run build → generated/sprint-test.json).
let builtin = null, builtinMtime = 0;
export function builtinQuestions() {
  const f = config.sprintTestFile;
  if (!fs.existsSync(f)) throw new Error('Sprint questions not found. Run `npm run build:portal` (creates ' + f + ').');
  const m = fs.statSync(f).mtimeMs;
  if (!builtin || m !== builtinMtime) { builtin = JSON.parse(fs.readFileSync(f, 'utf8')); builtinMtime = m; }
  return builtin;
}

// Questions of one Sprint: the set made in Admin → Sprint questions, or the built-in set when there is none.
// Answers are stored by position, so a set is locked once a student has started that Sprint (questions.js).
const qCache = new Map();
const Q_CACHE_MS = 5000;
export const rowToQuestion = (r) => {
  const q = { id: Number(r.id), course: r.course, unit: r.unit_id || '', type: 'mcq', q: r.q, o: parseJSON(r.options, []), c: Number(r.correct) };
  if (r.code) q.code = r.code;
  return q;
};
export async function getQuestions(sprintId) {
  if (!sprintId) sprintId = (await getSprint()).id;
  const hit = qCache.get(sprintId);
  if (hit && Date.now() - hit.at < Q_CACHE_MS) return hit.v;
  const rows = await all('SELECT * FROM sprint_questions WHERE sprint_id = ? ORDER BY position, id', sprintId);
  const v = rows.length ? rows.map(rowToQuestion) : builtinQuestions();
  if (qCache.size > 200) qCache.clear();
  qCache.set(sprintId, { at: Date.now(), v });
  return v;
}
export function clearQuestionCache(sprintId) { if (sprintId) qCache.delete(sprintId); else qCache.clear(); }

export async function publicQuestions(sprintId) {
  return (await getQuestions(sprintId)).map((q) => {
    const p = { course: q.course, type: q.type, q: q.q };
    if (q.code) p.code = q.code;
    if (q.type === 'mcq') p.o = q.o;
    if (q.type === 'code') { p.starter = q.starter || ''; p.sample = q.sample || ['', '']; p.testCount = (q.tests || []).length; }
    return p;
  });
}
export const questionTypes = async (sprintId) => (await getQuestions(sprintId)).map((q) => ({ course: q.course, type: q.type }));
export const maxTotal = async (sprintId) => (await getQuestions(sprintId)).reduce((s, q) => s + MARKS[q.type], 0);

export async function getSprint() {
  const s = config.sprint;
  const [id, title, open, close, dur, lb] = await Promise.all([
    getSetting('sprint_id', s.id), getSetting('sprint_title', 'Saturday Sprint'), getSetting('sprint_open', s.open),
    getSetting('sprint_close', s.close), getSetting('sprint_duration_min', s.durationMin), getSetting('leaderboard_visible', true)
  ]);
  const durationMin = Number(dur);
  return { id, title, open, close, durationMin, openMs: Date.parse(open), closeMs: Date.parse(close), durMs: durationMin * 60000, graceMs: s.graceMs, leaderboardVisible: lb };
}

const ADMIN_PREFIX = 'ADMIN-';
const attemptKey = (who) => (who.kind === 'admin' ? ADMIN_PREFIX + who.id : who.roll_no);

export async function getAttempt(who, sprint) {
  sprint = sprint || (await getSprint());
  return one('SELECT * FROM attempts WHERE sprint_id = ? AND roll_no = ?', sprint.id, attemptKey(who));
}

// ---------- autosave drafts: Redis when configured (keeps ~1,000 writes/s off Postgres at 15k users), else the attempts row
const draftKey = (a) => `draft:${a.id}`;
export async function readDraft(a) {
  if (kv.kvShared) { const d = await kv.get(draftKey(a)).catch(() => null); if (d) return typeof d === 'string' ? parseJSON(d, {}) : d; }
  return parseJSON(a.draft, {}) || {};
}
async function writeDraft(a, answers) {
  if (kv.kvShared) return kv.set(draftKey(a), answers, 2 * 86400);
  await run('UPDATE attempts SET draft = ?, updated_at = ? WHERE id = ? AND status = ?', JSON.stringify(answers), Date.now(), a.id, 'running');
}

export async function attemptView(a, { withQuestions = false } = {}) {
  if (!a) return { status: 'none' };
  const v = { status: a.status, startedAt: a.started_at, deadlineAt: a.deadline_at };
  if (a.status === 'running') {
    v.draft = await readDraft(a);
    if (withQuestions) v.questions = await publicQuestions(a.sprint_id);
  } else {
    v.submittedAt = a.submitted_at;
    v.result = resultView(a);
  }
  return v;
}

export function resultView(a) {
  const d = parseJSON(a.detail, {});
  return {
    mcqRight: d.mcqRight ?? 0, mcqN: d.mcqN ?? 0, probDone: d.probDone ?? 0, probN: d.probN ?? 0,
    codeRes: d.codeRes || {}, score: a.total, maxTotal: a.max_total, mcqScore: a.mcq_score, codeScore: a.code_score,
    textScore: a.text_score, textPending: d.textN > 0 && !a.text_reviewed,
    usedMs: a.used_ms, submittedAt: a.submitted_at, autoSubmitted: !!a.auto_submitted,
    endedByViolations: (parseJSON(a.proctor, null) || {}).endedBy === 'violations'
  };
}

export class SprintError extends Error {
  constructor(code, message, status = 400) { super(message); this.code = code; this.status = status; }
}

export async function startAttempt(who) {
  const sprint = await getSprint(), now = Date.now();
  const existing = await getAttempt(who, sprint);
  if (who.kind === 'admin') {
    if (existing && existing.status === 'submitted') { await run('DELETE FROM attempt_events WHERE attempt_id = ?', existing.id); await run('DELETE FROM attempts WHERE id = ?', existing.id); }
    else if (existing) return existing;
  } else {
    if (existing && existing.status === 'running') return existing;
    if (existing) throw new SprintError('ALREADY_SUBMITTED', 'You have already submitted this Sprint.', 409);
    if (now < sprint.openMs) throw new SprintError('NOT_OPEN', 'The Sprint has not opened yet.', 403);
    if (now >= sprint.closeMs) throw new SprintError('CLOSED', 'The Sprint has closed.', 403);
  }
  const deadline = who.kind === 'admin' ? now + sprint.durMs : Math.min(now + sprint.durMs, sprint.closeMs);
  await run(`INSERT INTO attempts (sprint_id, roll_no, status, started_at, deadline_at, draft, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)
             ON CONFLICT (sprint_id, roll_no) DO NOTHING`, sprint.id, attemptKey(who), 'running', now, deadline, '{}', now);
  return getAttempt(who, sprint);
}

export function cleanAnswers(body, qs) {
  const out = { mcq: {}, text: {}, code: {} };
  const src = body || {};
  qs.forEach((q, i) => {
    if (q.type === 'mcq') {
      const v = src.mcq && src.mcq[i];
      if (Number.isInteger(v) && v >= 0 && v < q.o.length) out.mcq[i] = v;
    } else if (q.type === 'text') {
      const v = src.text && src.text[i];
      if (typeof v === 'string' && v.trim()) out.text[i] = v.slice(0, 20000);
    } else if (q.type === 'code') {
      const v = src.code && src.code[i];
      if (typeof v === 'string') out.code[i] = v.slice(0, 20000);
    }
  });
  return out;
}

export async function saveDraft(who, body) {
  const a = await getAttempt(who);
  if (!a || a.status !== 'running') throw new SprintError('NOT_RUNNING', 'No Sprint in progress.', 409);
  const sprint = await getSprint();
  if (Date.now() > a.deadline_at + sprint.graceMs) throw new SprintError('TIME_UP', 'Time is up.', 409);
  await writeDraft(a, cleanAnswers(body, await getQuestions(a.sprint_id)));
}

export async function checkCode(who, index, code) {
  const a = await getAttempt(who);
  if (!a || a.status !== 'running') throw new SprintError('NOT_RUNNING', 'No Sprint in progress.', 409);
  const q = (await getQuestions(a.sprint_id))[index];
  if (!q || q.type !== 'code') throw new SprintError('BAD_QUESTION', 'Not a coding question.');
  const r = await runTests(String(code || '').slice(0, 20000), q.tests);
  return r.map((x) => ({ pass: x.pass }));
}

async function grade(answers, prevDetail, qs) {
  let mcqRight = 0, mcqN = 0, codeScore = 0, probDone = 0, probN = 0, textN = 0, maxT = 0, textScore = 0;
  const codeRes = {}, perQ = [];
  const textMarks = (prevDetail && prevDetail.textMarks) || {};
  for (let i = 0; i < qs.length; i++) {
    const q = qs[i];
    if (q.type === 'mcq') {
      mcqN++; maxT += MARKS.mcq;
      const pick = answers.mcq[i], ok = pick === q.c;
      if (ok) mcqRight++;
      perQ.push({ i, type: 'mcq', pick: pick ?? null, correct: q.c, ok });
    } else if (q.type === 'code') {
      probN++; maxT += MARKS.code;
      const code = answers.code[i], total = q.tests.length;
      let pass = 0;
      if (code && code.trim() && code !== q.starter) {
        try { pass = (await runTests(code, q.tests)).filter((x) => x.pass).length; } catch (e) { console.error('[grade] code question', i, e.message); }
      }
      codeRes[i] = { pass, total };
      if (pass === total) probDone++;
      codeScore += total ? MARKS.code * pass / total : 0;
      perQ.push({ i, type: 'code', pass, total });
    } else {
      probN++; textN++; maxT += MARKS.text;
      const answered = !!(answers.text[i] || '').trim();
      if (answered) probDone++;
      const m = Number(textMarks[i] || 0);
      textScore += m;
      perQ.push({ i, type: 'text', answered, mark: textMarks[i] ?? null });
    }
  }
  const r2 = (x) => Math.round(x * 100) / 100;
  return {
    mcqScore: mcqRight * MARKS.mcq, codeScore: r2(codeScore), textScore: r2(textScore), maxTotal: maxT,
    total: r2(mcqRight * MARKS.mcq + codeScore + textScore),
    detail: { mcqRight, mcqN, codeRes, probDone, probN, textN, textMarks, perQ }
  };
}

export const finalizeAttempt = (a, answers, auto) => finalize(a, answers, auto);
async function finalize(a, answers, auto) {
  // Only one instance grades a given attempt.
  if (!(await kv.setNX('grading:' + a.id, '1', 60))) throw new SprintError('BUSY', 'Already grading. Try again in a moment.', 409);
  try {
    const g = await grade(answers, parseJSON(a.detail, {}), await getQuestions(a.sprint_id));
    const now = Date.now(), submittedAt = auto ? Math.min(now, a.deadline_at) : now;
    const used = Math.max(0, Math.min(submittedAt, a.deadline_at) - a.started_at);
    await run(`UPDATE attempts SET status = 'submitted', submitted_at = ?, auto_submitted = ?, answers = ?, detail = ?, mcq_score = ?, code_score = ?,
         text_score = ?, total = ?, max_total = ?, used_ms = ?, draft = NULL, text_reviewed = ?, updated_at = ? WHERE id = ? AND status = 'running'`,
      submittedAt, auto ? 1 : 0, JSON.stringify(answers), JSON.stringify(g.detail), g.mcqScore, g.codeScore, g.textScore, g.total, g.maxTotal, used,
      g.detail.textN ? 0 : 1, now, a.id); // nothing to mark when the test has no written questions
    if (kv.kvShared) kv.del(draftKey(a)).catch(() => {});
    return one('SELECT * FROM attempts WHERE id = ?', a.id);
  } finally {
    kv.del('grading:' + a.id).catch(() => {});
  }
}

export async function submitAttempt(who, body) {
  const a = await getAttempt(who);
  if (!a) throw new SprintError('NOT_STARTED', 'You have not started the Sprint.', 409);
  if (a.status === 'submitted') return a;
  const late = Date.now() > a.deadline_at + (await getSprint()).graceMs;
  const qs = await getQuestions(a.sprint_id);
  const answers = late ? cleanAnswers(await readDraft(a), qs) : cleanAnswers(body, qs);
  if (!late) writeDraft(a, answers).catch(() => {}); // keep the latest answers if grading is interrupted
  return finalize(a, answers, late);
}

// Auto-submit attempts whose time ran out without a submit. Run by Vercel Cron every minute (and by the local server).
export async function finalizeExpired({ limit = 300, budgetMs = 45000 } = {}) {
  const grace = config.sprint.graceMs, t0 = Date.now();
  const due = await all("SELECT * FROM attempts WHERE status = 'running' AND deadline_at + ? < ? ORDER BY deadline_at LIMIT ?", grace, Date.now(), limit);
  let done = 0;
  for (let i = 0; i < due.length && Date.now() - t0 < budgetMs; i += 8) {
    await Promise.all(due.slice(i, i + 8).map(async (a) => {
      try { await finalize(a, cleanAnswers(await readDraft(a), await getQuestions(a.sprint_id)), true); done++; } catch (e) { if (e.code !== 'BUSY') console.error('[sprint] auto-submit failed', a.id, e.message); }
    }));
  }
  if (done) await clearBoardCache();
  return done;
}

export async function setTextMarks(attemptId, marks) {
  const a = await one('SELECT * FROM attempts WHERE id = ?', attemptId);
  if (!a || a.status !== 'submitted') throw new SprintError('NOT_FOUND', 'Submitted attempt not found.', 404);
  const qs = await getQuestions(a.sprint_id), d = parseJSON(a.detail, {});
  const tm = { ...(d.textMarks || {}) };
  for (const [k, v] of Object.entries(marks || {})) {
    const i = Number(k);
    if (!qs[i] || qs[i].type !== 'text') continue;
    if (v === null || v === '') { delete tm[i]; continue; }
    const n = Number(v);
    if (!Number.isFinite(n) || n < 0 || n > MARKS.text) throw new SprintError('BAD_MARK', `Marks must be between 0 and ${MARKS.text}.`);
    tm[i] = Math.round(n * 100) / 100;
  }
  const textScore = Object.values(tm).reduce((s, x) => s + x, 0);
  d.textMarks = tm;
  (d.perQ || []).forEach((p) => { if (p.type === 'text') p.mark = tm[p.i] ?? null; });
  const reviewed = qs.every((q, i) => q.type !== 'text' || tm[i] !== undefined) ? 1 : 0;
  const total = Math.round(((a.mcq_score || 0) + (a.code_score || 0) + textScore) * 100) / 100;
  await run('UPDATE attempts SET detail = ?, text_score = ?, text_reviewed = ?, total = ?, updated_at = ? WHERE id = ?',
    JSON.stringify(d), textScore, reviewed, total, Date.now(), a.id);
  await clearBoardCache();
  return one('SELECT * FROM attempts WHERE id = ?', a.id);
}

// ---------- leaderboard
// Rank: higher score first; equal score → less time (whole seconds) first; equal score AND time share a rank.
export const RANK_RULE = 'Ranked by total score (high to low). Ties are broken by time taken (less is better). Equal score and equal time share a rank.';
// In production, test students (batch TEST, see scripts/test-accounts.js) never appear on the leaderboard.
const ELIGIBLE = `a.sprint_id = ? AND a.status = 'submitted' AND m.active = 1 AND (u.status IS NULL OR u.status = 'active')` +
  (config.isLive ? ` AND m.batch <> 'TEST'` : '');
const FROM = `FROM attempts a JOIN students_master m ON m.roll_no = a.roll_no LEFT JOIN users u ON u.roll_no = a.roll_no`;

// Full ranked list (admin views, exports).
export async function leaderboardRows(sprintId, limit = 100000) {
  return all(`SELECT a.id, a.roll_no, m.name, m.batch, a.total, a.max_total, a.used_ms, a.submitted_at, a.mcq_score, a.code_score, a.text_score, a.text_reviewed,
           RANK() OVER (ORDER BY a.total DESC, (a.used_ms / 1000) ASC) AS rank
    ${FROM} WHERE ${ELIGIBLE} ORDER BY rank ASC, a.submitted_at ASC LIMIT ?`, sprintId, limit);
}

const publicRow = (r, meRoll) => ({
  rank: r.rank, name: r.name || 'Student', id: maskRoll(r.roll_no), batch: r.batch, score: r.total, maxTotal: r.max_total,
  usedMs: r.used_ms, me: r.roll_no === meRoll
});

const boardKey = (sprintId) => 'lb:v1:' + sprintId;
export async function clearBoardCache() {
  const s = await getSprint();
  await kv.invalidate(boardKey(s.id));
  myRank.clear();
}

// Top of the board: computed at most once per 5 s across all instances (Redis), ~free per request.
async function boardTop(sprintId) {
  return kv.cached(boardKey(sprintId), 5, async () => {
    const [rows, cnt] = await Promise.all([
      leaderboardRows(sprintId, 100),
      one(`SELECT COUNT(*) AS n ${FROM} WHERE ${ELIGIBLE}`, sprintId)
    ]);
    return { rows: rows.map((r) => ({ rank: r.rank, roll_no: r.roll_no, name: r.name, batch: r.batch, total: r.total, max_total: r.max_total, used_ms: r.used_ms })), participants: cnt.n, at: Date.now() };
  });
}

// One student's rank without loading the whole board (cached per instance for 10 s).
const myRank = new Map();
async function rankOf(sprintId, roll) {
  const k = sprintId + '|' + roll, hit = myRank.get(k);
  if (hit && Date.now() - hit.at < 10000) return hit.v;
  const me = await one(`SELECT a.roll_no, m.name, m.batch, a.total, a.max_total, a.used_ms ${FROM} WHERE ${ELIGIBLE} AND a.roll_no = ?`, sprintId, roll);
  let v = null;
  if (me) {
    const ahead = await one(`SELECT COUNT(*) AS n ${FROM} WHERE ${ELIGIBLE} AND (a.total > ? OR (a.total = ? AND (a.used_ms / 1000) < ?))`,
      sprintId, me.total, me.total, Math.floor(me.used_ms / 1000));
    v = { ...me, rank: ahead.n + 1 };
  }
  if (myRank.size > 50000) myRank.clear();
  myRank.set(k, { at: Date.now(), v });
  return v;
}

export async function leaderboard(meRoll, limit = 50) {
  const sprint = await getSprint();
  const top = await boardTop(sprint.id);
  const mine = meRoll ? await rankOf(sprint.id, meRoll) : null;
  return {
    sprintId: sprint.id, title: sprint.title, rule: RANK_RULE, participants: top.participants, updatedAt: top.at,
    rows: top.rows.slice(0, limit).map((r) => publicRow(r, meRoll)),
    me: mine ? publicRow(mine, meRoll) : null
  };
}
